# Generated by Django 5.0 on 2026-02-18 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('brand', models.CharField(max_length=300)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(max_length=100)),
                ('mouthSize', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('currentQuantity', models.IntegerField()),
                ('supplierName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyInventoryApp.supplier')),
            ],
        ),
    ]
